---
##### Down and dirty laptop setup for macOS
##### No guarantees this will work for anyone else. 
##### This was literally written as I cobbled my new laptop together.

- hosts: localhost
  gather_facts: true

  vars_files: 
    - defaults/main.yml

  roles:
    - { role: brew_packages }
 
  tasks:
    - name: Create home for code
      file: 
        path: "{{ repo_home }}"
        state: directory
      register: repo_home
    
    - include_tasks: tasks/dotfiles.yml
      when: repo_home is succeeded
      tags: 
        - dotfiles

    - include_tasks: tasks/sshkeys.yml

    # TODO: Add homebrew cask-drivers for displaylink driver setup (for Targus docking station)
    #brew tap homebrew/cask-drivers
    #brew cask install displaylink

    # TODO:  Add Finder and Dock preferences

    # TODO: Add FileVault encryption