---
##### Down and dirty laptop setup for macOS
##### No guarantees this will work for anyone else. 
##### This was literally written as I cobbled my new laptop together.

- hosts: localhost
  gather_facts: true

  vars_files: defaults/main.yml

  vars:
    brew_packages:
      - git
      - vim
      - go
      - fortune
      - cowsay
      - lolcat
    brew_cask_packages:
      - visual-studio-code
      - iterm2
      - google-chrome
      - spotify
      - docker
      - slack
      - amethyst
      - keepassx
      - onedrive
      - virtualbox
    dotfiles:
      - bash_profile
      - profile
      - bashrc
      - vimrc
      - vim
 
  tasks:
    - name: brew install packages
      homebrew: 
        name:
          "{{ brew_packages }}"
        state: present
      tags:
        - install

    - name: brew cask install packages
      homebrew_cask:
        name:
          "{{ brew_cask_packages }}"
        state: present
      tags:
        - install

    - name: Create home for code
      file: 
        path: "{{ repo_home }}"
        state: directory
    
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/sshkeys.yml

    # TODO: Add homebrew cask-drivers for displaylink driver setup (for Targus docking station)
    #brew tap homebrew/cask-drivers
    #brew cask install displaylink

    # TODO: Add amythyst Accessibility allowance & start on login

    # TODO:  Add Finder and Dock preferences

    # TODO: Add FileVault encryption