---
# defaults file for brew_packages

brew_packages:
  - git
  - vim
  - go
  - fortune
  - cowsay
  - lolcat
  - tree
brew_cask_packages:
  - visual-studio-code
  - iterm2
  - google-chrome
  - spotify
  - docker
  - slack
  - keepassx
  - virtualbox
  - signal
  - istat-menus
  - microsoft-office